region: "us-east-2"
identifier: "alisa"

vpc:
  create_vpc: true
  cidr: "10.0.0.0/16"
  azs: ["us-east-1a", "us-east-1b", "us-east-1c"]
  private_subnets: ["10.0.2.0/24", "10.0.3.0/24", "10.0.4.0/24"]
  public_subnets: ["10.0.102.0/24", "10.0.103.0/24", "10.0.104.0/24"]
  intra_subnets: ["10.0.52.0/24", "10.0.53.0/24", "10.0.54.0/24"]
  enable_nat_gateway: true
  enable_vpn_gateway: false
  single_nat_gateway: true
  one_nat_gateway_per_az: false
  create_flow_log_cloudwatch_iam_role: true
  create_flow_log_cloudwatch_log_group: true
  enable_flow_log: true
  flow_log_file_format: "plain-text"

tags: 
  ManagedBy: "terraform"