region: "us-east-2"
identifier: "alisa"
profile: "pinulito-prod"

vpc:
  create_vpc: true
  cidr: "10.1.0.0/16"
  azs: ["us-east-2a", "us-east-2b", "us-east-2c"]
  private_subnets: ["10.1.2.0/24", "10.1.3.0/24", "10.1.4.0/24"]
  public_subnets: ["10.1.102.0/24", "10.1.103.0/24", "10.1.104.0/24"]
  intra_subnets: ["10.1.52.0/24", "10.1.53.0/24", "10.1.54.0/24"]
  enable_nat_gateway: true
  enable_vpn_gateway: false
  single_nat_gateway: true
  one_nat_gateway_per_az: false
  create_flow_log_cloudwatch_iam_role: true
  create_flow_log_cloudwatch_log_group: true
  enable_flow_log: true
  flow_log_file_format: "plain-text"

transit:
  network:
    create: false
    auto_accept_attachments: true
    share_tgw: true
    ram_external_principals: true
    ram_principals: []
    routes: []
  
  customer: 
    create: true
    owner: 823613469731
    route: "10.0.0.0/16"
  

tags: 
  ManagedBy: "terraform"